export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const RETRIEVE_USER = "RETRIEVE_USER";
export const DELETE_USER = "DELETE_USER";

export const RETRIEVE_HOUSEHOLDS_SUCCESS = "RETRIEVE_HOUSEHOLDS_SUCCESS";
export const RETRIEVE_HOUSEHOLDS_FAIL = "RETRIEVE_HOUSEHOLDS_FAIL";
export const RETRIEVE_HOUSEHOLDS_BEGIN = "RETRIEVE_HOUSEHOLDS_BEGIN";

export const RETRIEVE_ONEA_SUCCESS = "RETRIEVE_TRANSACTIONS_SUCCESS";
export const RETRIEVE_ONEA_FAIL = "RETRIEVE_TRANSACTIONS_FAIL";
export const RETRIEVE_ONEA_BEGIN = "RETRIEVE_TRANSACTIONS_BEGIN";

export const RETRIEVE_CATEGORIES_SUCCESS = "RETRIEVE_CATEGORIES_SUCCESS";
export const RETRIEVE_CATEGORIES_FAIL = "RETRIEVE_CATEGORIES_FAIL";
export const RETRIEVE_CATEGORIES_BEGIN = "RETRIEVE_CATEGORIES_BEGIN";

export const POST_HOUSEHOLDS_SUCCESS = "RETRIEVE_HOUSEHOLDS_SUCCESS";
export const POST_HOUSEHOLDS_FAIL = "RETRIEVE_HOUSEHOLDS_FAIL";
export const POST_HOUSEHOLDS_BEGIN = "RETRIEVE_HOUSEHOLDS_BEGIN";

export const UPLOAD_HOUSHOLDS_BEGIN ="UPLOAD_HOUSHOLDS_BEGIN";
export const UPLOAD_HOUSHOLDS_SUCCESS = "UPLOAD_HOUSHOLDS_SUCCESS";
export const UPLOAD_HOUSHOLDS_FAIL = "UPLOAD_HOUSHOLDS_FAIL";

export const RETRIEVE_HSHDS_BEGIN = "RETRIEVE_HSHDS_BEGIN";
export const RETRIEVE_HSHDS_SUCCESS = "RETRIEVE_HSHDS_SUCCESS";
export const RETRIEVE_HSHDS_FAIL = "RETRIEVE_HSHDS_FAIL";

export const RETRIEVE_TWOA_BEGIN = "RETRIEVE_TWOA_BEGIN";
export const RETRIEVE_TWOA_SUCCESS = "RETRIEVE_TWOA_SUCCESS";
export const RETRIEVE_TWOA_FAIL = "RETRIEVE_TWOA_FAIL";

